/**
 * City -> IANA timezone resolver. Pure data, no I/O.
 * Used so the bot can render the user's local time even when only a city is mentioned
 * (no GPS share, so no Open-Meteo timezone field).
 */

const CITY_TZ = {
  // North America
  'new york': 'America/New_York',
  'nyc': 'America/New_York',
  'boston': 'America/New_York',
  'philadelphia': 'America/New_York',
  'washington': 'America/New_York',
  'washington dc': 'America/New_York',
  'miami': 'America/New_York',
  'orlando': 'America/New_York',
  'atlanta': 'America/New_York',
  'detroit': 'America/Detroit',
  'pittsburgh': 'America/New_York',
  'baltimore': 'America/New_York',
  'charlotte': 'America/New_York',
  'tampa': 'America/New_York',
  'nashville': 'America/Chicago',
  'new orleans': 'America/Chicago',
  'chicago': 'America/Chicago',
  'houston': 'America/Chicago',
  'dallas': 'America/Chicago',
  'austin': 'America/Chicago',
  'san antonio': 'America/Chicago',
  'minneapolis': 'America/Chicago',
  'st louis': 'America/Chicago',
  'kansas city': 'America/Chicago',
  'memphis': 'America/Chicago',
  'oklahoma city': 'America/Chicago',
  'milwaukee': 'America/Chicago',
  'denver': 'America/Denver',
  'salt lake city': 'America/Denver',
  'albuquerque': 'America/Denver',
  'phoenix': 'America/Phoenix',
  'tucson': 'America/Phoenix',
  'las vegas': 'America/Los_Angeles',
  'los angeles': 'America/Los_Angeles',
  'la': 'America/Los_Angeles',
  'san francisco': 'America/Los_Angeles',
  'san diego': 'America/Los_Angeles',
  'san jose': 'America/Los_Angeles',
  'sacramento': 'America/Los_Angeles',
  'seattle': 'America/Los_Angeles',
  'portland': 'America/Los_Angeles',
  'anchorage': 'America/Anchorage',
  'honolulu': 'Pacific/Honolulu',
  'toronto': 'America/Toronto',
  'ottawa': 'America/Toronto',
  'montreal': 'America/Montreal',
  'quebec': 'America/Montreal',
  'vancouver': 'America/Vancouver',
  'calgary': 'America/Edmonton',
  'edmonton': 'America/Edmonton',
  'winnipeg': 'America/Winnipeg',
  'halifax': 'America/Halifax',
  'mexico city': 'America/Mexico_City',
  'cancun': 'America/Cancun',
  'guadalajara': 'America/Mexico_City',
  'monterrey': 'America/Monterrey',
  'tijuana': 'America/Tijuana',
  'havana': 'America/Havana',
  'san juan': 'America/Puerto_Rico',
  'kingston': 'America/Jamaica',
  'panama city': 'America/Panama',
  'guatemala city': 'America/Guatemala',
  'san salvador': 'America/El_Salvador',
  'tegucigalpa': 'America/Tegucigalpa',
  'managua': 'America/Managua',
  'san jose costa rica': 'America/Costa_Rica',

  // South America
  'rio': 'America/Sao_Paulo',
  'rio de janeiro': 'America/Sao_Paulo',
  'sao paulo': 'America/Sao_Paulo',
  'brasilia': 'America/Sao_Paulo',
  'salvador': 'America/Bahia',
  'recife': 'America/Recife',
  'manaus': 'America/Manaus',
  'buenos aires': 'America/Argentina/Buenos_Aires',
  'cordoba': 'America/Argentina/Cordoba',
  'mendoza': 'America/Argentina/Mendoza',
  'santiago': 'America/Santiago',
  'lima': 'America/Lima',
  'cusco': 'America/Lima',
  'bogota': 'America/Bogota',
  'medellin': 'America/Bogota',
  'cartagena': 'America/Bogota',
  'cali': 'America/Bogota',
  'quito': 'America/Guayaquil',
  'guayaquil': 'America/Guayaquil',
  'caracas': 'America/Caracas',
  'la paz': 'America/La_Paz',
  'asuncion': 'America/Asuncion',
  'montevideo': 'America/Montevideo',
  'georgetown': 'America/Guyana',
  'paramaribo': 'America/Paramaribo',

  // Western Europe
  'london': 'Europe/London',
  'manchester': 'Europe/London',
  'birmingham': 'Europe/London',
  'liverpool': 'Europe/London',
  'leeds': 'Europe/London',
  'glasgow': 'Europe/London',
  'edinburgh': 'Europe/London',
  'cardiff': 'Europe/London',
  'belfast': 'Europe/London',
  'dublin': 'Europe/Dublin',
  'cork': 'Europe/Dublin',
  'paris': 'Europe/Paris',
  'lyon': 'Europe/Paris',
  'marseille': 'Europe/Paris',
  'nice': 'Europe/Paris',
  'bordeaux': 'Europe/Paris',
  'toulouse': 'Europe/Paris',
  'strasbourg': 'Europe/Paris',
  'amsterdam': 'Europe/Amsterdam',
  'rotterdam': 'Europe/Amsterdam',
  'the hague': 'Europe/Amsterdam',
  'utrecht': 'Europe/Amsterdam',
  'brussels': 'Europe/Brussels',
  'antwerp': 'Europe/Brussels',
  'bruges': 'Europe/Brussels',
  'luxembourg': 'Europe/Luxembourg',
  'berlin': 'Europe/Berlin',
  'munich': 'Europe/Berlin',
  'hamburg': 'Europe/Berlin',
  'frankfurt': 'Europe/Berlin',
  'cologne': 'Europe/Berlin',
  'stuttgart': 'Europe/Berlin',
  'dusseldorf': 'Europe/Berlin',
  'leipzig': 'Europe/Berlin',
  'dresden': 'Europe/Berlin',
  'vienna': 'Europe/Vienna',
  'salzburg': 'Europe/Vienna',
  'innsbruck': 'Europe/Vienna',
  'zurich': 'Europe/Zurich',
  'geneva': 'Europe/Zurich',
  'bern': 'Europe/Zurich',
  'basel': 'Europe/Zurich',
  'rome': 'Europe/Rome',
  'milan': 'Europe/Rome',
  'naples': 'Europe/Rome',
  'florence': 'Europe/Rome',
  'venice': 'Europe/Rome',
  'turin': 'Europe/Rome',
  'bologna': 'Europe/Rome',
  'palermo': 'Europe/Rome',
  'madrid': 'Europe/Madrid',
  'barcelona': 'Europe/Madrid',
  'valencia': 'Europe/Madrid',
  'seville': 'Europe/Madrid',
  'malaga': 'Europe/Madrid',
  'bilbao': 'Europe/Madrid',
  'granada': 'Europe/Madrid',
  'lisbon': 'Europe/Lisbon',
  'porto': 'Europe/Lisbon',

  // Northern Europe
  'stockholm': 'Europe/Stockholm',
  'gothenburg': 'Europe/Stockholm',
  'oslo': 'Europe/Oslo',
  'bergen': 'Europe/Oslo',
  'copenhagen': 'Europe/Copenhagen',
  'helsinki': 'Europe/Helsinki',
  'reykjavik': 'Atlantic/Reykjavik',
  'tallinn': 'Europe/Tallinn',
  'riga': 'Europe/Riga',
  'vilnius': 'Europe/Vilnius',

  // Eastern Europe
  'prague': 'Europe/Prague',
  'warsaw': 'Europe/Warsaw',
  'krakow': 'Europe/Warsaw',
  'gdansk': 'Europe/Warsaw',
  'budapest': 'Europe/Budapest',
  'bratislava': 'Europe/Bratislava',
  'ljubljana': 'Europe/Ljubljana',
  'zagreb': 'Europe/Zagreb',
  'belgrade': 'Europe/Belgrade',
  'sarajevo': 'Europe/Sarajevo',
  'skopje': 'Europe/Skopje',
  'tirana': 'Europe/Tirane',
  'sofia': 'Europe/Sofia',
  'bucharest': 'Europe/Bucharest',
  'athens': 'Europe/Athens',
  'thessaloniki': 'Europe/Athens',
  'istanbul': 'Europe/Istanbul',
  'ankara': 'Europe/Istanbul',
  'izmir': 'Europe/Istanbul',
  'antalya': 'Europe/Istanbul',
  'kiev': 'Europe/Kiev',
  'kyiv': 'Europe/Kiev',
  'moscow': 'Europe/Moscow',
  'st petersburg': 'Europe/Moscow',
  'saint petersburg': 'Europe/Moscow',
  'minsk': 'Europe/Minsk',

  // Middle East
  'dubai': 'Asia/Dubai',
  'abu dhabi': 'Asia/Dubai',
  'sharjah': 'Asia/Dubai',
  'doha': 'Asia/Qatar',
  'riyadh': 'Asia/Riyadh',
  'jeddah': 'Asia/Riyadh',
  'mecca': 'Asia/Riyadh',
  'kuwait city': 'Asia/Kuwait',
  'manama': 'Asia/Bahrain',
  'muscat': 'Asia/Muscat',
  'tehran': 'Asia/Tehran',
  'baghdad': 'Asia/Baghdad',
  'beirut': 'Asia/Beirut',
  'damascus': 'Asia/Damascus',
  'amman': 'Asia/Amman',
  'jerusalem': 'Asia/Jerusalem',
  'tel aviv': 'Asia/Tel_Aviv',

  // Africa
  'cairo': 'Africa/Cairo',
  'alexandria': 'Africa/Cairo',
  'casablanca': 'Africa/Casablanca',
  'marrakech': 'Africa/Casablanca',
  'rabat': 'Africa/Casablanca',
  'tunis': 'Africa/Tunis',
  'algiers': 'Africa/Algiers',
  'lagos': 'Africa/Lagos',
  'abuja': 'Africa/Lagos',
  'accra': 'Africa/Accra',
  'addis ababa': 'Africa/Addis_Ababa',
  'nairobi': 'Africa/Nairobi',
  'mombasa': 'Africa/Nairobi',
  'kampala': 'Africa/Kampala',
  'dar es salaam': 'Africa/Dar_es_Salaam',
  'zanzibar': 'Africa/Dar_es_Salaam',
  'kigali': 'Africa/Kigali',
  'johannesburg': 'Africa/Johannesburg',
  'cape town': 'Africa/Johannesburg',
  'durban': 'Africa/Johannesburg',
  'pretoria': 'Africa/Johannesburg',
  'harare': 'Africa/Harare',
  'lusaka': 'Africa/Lusaka',
  'maputo': 'Africa/Maputo',
  'gaborone': 'Africa/Gaborone',
  'windhoek': 'Africa/Windhoek',
  'mauritius': 'Indian/Mauritius',
  'port louis': 'Indian/Mauritius',

  // South Asia
  'mumbai': 'Asia/Kolkata',
  'delhi': 'Asia/Kolkata',
  'new delhi': 'Asia/Kolkata',
  'kolkata': 'Asia/Kolkata',
  'calcutta': 'Asia/Kolkata',
  'chennai': 'Asia/Kolkata',
  'madras': 'Asia/Kolkata',
  'bangalore': 'Asia/Kolkata',
  'bengaluru': 'Asia/Kolkata',
  'hyderabad': 'Asia/Kolkata',
  'pune': 'Asia/Kolkata',
  'ahmedabad': 'Asia/Kolkata',
  'lucknow': 'Asia/Kolkata',
  'jaipur': 'Asia/Kolkata',
  'agra': 'Asia/Kolkata',
  'varanasi': 'Asia/Kolkata',
  'goa': 'Asia/Kolkata',
  'chandigarh': 'Asia/Kolkata',
  'shimla': 'Asia/Kolkata',
  'manali': 'Asia/Kolkata',
  'rishikesh': 'Asia/Kolkata',
  'udaipur': 'Asia/Kolkata',
  'jodhpur': 'Asia/Kolkata',
  'kochi': 'Asia/Kolkata',
  'kerala': 'Asia/Kolkata',
  'amritsar': 'Asia/Kolkata',
  'darjeeling': 'Asia/Kolkata',
  'kathmandu': 'Asia/Kathmandu',
  'pokhara': 'Asia/Kathmandu',
  'dhaka': 'Asia/Dhaka',
  'colombo': 'Asia/Colombo',
  'thimphu': 'Asia/Thimphu',
  'male': 'Indian/Maldives',
  'islamabad': 'Asia/Karachi',
  'karachi': 'Asia/Karachi',
  'lahore': 'Asia/Karachi',
  'kabul': 'Asia/Kabul',

  // Southeast Asia
  'bangkok': 'Asia/Bangkok',
  'chiang mai': 'Asia/Bangkok',
  'phuket': 'Asia/Bangkok',
  'krabi': 'Asia/Bangkok',
  'pattaya': 'Asia/Bangkok',
  'singapore': 'Asia/Singapore',
  'kuala lumpur': 'Asia/Kuala_Lumpur',
  'penang': 'Asia/Kuala_Lumpur',
  'jakarta': 'Asia/Jakarta',
  'bali': 'Asia/Makassar',
  'denpasar': 'Asia/Makassar',
  'ubud': 'Asia/Makassar',
  'surabaya': 'Asia/Jakarta',
  'manila': 'Asia/Manila',
  'cebu': 'Asia/Manila',
  'hanoi': 'Asia/Ho_Chi_Minh',
  'ho chi minh': 'Asia/Ho_Chi_Minh',
  'ho chi minh city': 'Asia/Ho_Chi_Minh',
  'saigon': 'Asia/Ho_Chi_Minh',
  'da nang': 'Asia/Ho_Chi_Minh',
  'hoi an': 'Asia/Ho_Chi_Minh',
  'phnom penh': 'Asia/Phnom_Penh',
  'siem reap': 'Asia/Phnom_Penh',
  'vientiane': 'Asia/Vientiane',
  'yangon': 'Asia/Yangon',
  'rangoon': 'Asia/Yangon',

  // East Asia
  'tokyo': 'Asia/Tokyo',
  'osaka': 'Asia/Tokyo',
  'kyoto': 'Asia/Tokyo',
  'yokohama': 'Asia/Tokyo',
  'sapporo': 'Asia/Tokyo',
  'fukuoka': 'Asia/Tokyo',
  'hiroshima': 'Asia/Tokyo',
  'nagoya': 'Asia/Tokyo',
  'seoul': 'Asia/Seoul',
  'busan': 'Asia/Seoul',
  'incheon': 'Asia/Seoul',
  'jeju': 'Asia/Seoul',
  'pyongyang': 'Asia/Pyongyang',
  'beijing': 'Asia/Shanghai',
  'shanghai': 'Asia/Shanghai',
  'guangzhou': 'Asia/Shanghai',
  'shenzhen': 'Asia/Shanghai',
  'chengdu': 'Asia/Shanghai',
  'xian': 'Asia/Shanghai',
  'hong kong': 'Asia/Hong_Kong',
  'macau': 'Asia/Macau',
  'macao': 'Asia/Macau',
  'taipei': 'Asia/Taipei',
  'taichung': 'Asia/Taipei',
  'kaohsiung': 'Asia/Taipei',
  'ulaanbaatar': 'Asia/Ulaanbaatar',

  // Oceania
  'sydney': 'Australia/Sydney',
  'melbourne': 'Australia/Melbourne',
  'brisbane': 'Australia/Brisbane',
  'gold coast': 'Australia/Brisbane',
  'cairns': 'Australia/Brisbane',
  'perth': 'Australia/Perth',
  'adelaide': 'Australia/Adelaide',
  'hobart': 'Australia/Hobart',
  'darwin': 'Australia/Darwin',
  'canberra': 'Australia/Sydney',
  'auckland': 'Pacific/Auckland',
  'wellington': 'Pacific/Auckland',
  'christchurch': 'Pacific/Auckland',
  'queenstown': 'Pacific/Auckland',
  'suva': 'Pacific/Fiji',
  'nadi': 'Pacific/Fiji',
  'apia': 'Pacific/Apia',
  'papeete': 'Pacific/Tahiti',

  // Central Asia
  'tashkent': 'Asia/Tashkent',
  'samarkand': 'Asia/Samarkand',
  'almaty': 'Asia/Almaty',
  'astana': 'Asia/Almaty',
  'nur sultan': 'Asia/Almaty',
  'bishkek': 'Asia/Bishkek',
  'dushanbe': 'Asia/Dushanbe',
  'ashgabat': 'Asia/Ashgabat',
  'baku': 'Asia/Baku',
  'tbilisi': 'Asia/Tbilisi',
  'yerevan': 'Asia/Yerevan',
};

// Single-timezone or dominant-timezone country fallbacks. Multi-tz countries
// (US, Russia, Australia, Brazil, Canada, Mexico, Indonesia, Kazakhstan) intentionally
// return null so callers fall back to city-level resolution.
const COUNTRY_TZ = {
  'india': 'Asia/Kolkata',
  'pakistan': 'Asia/Karachi',
  'bangladesh': 'Asia/Dhaka',
  'sri lanka': 'Asia/Colombo',
  'nepal': 'Asia/Kathmandu',
  'bhutan': 'Asia/Thimphu',
  'maldives': 'Indian/Maldives',
  'afghanistan': 'Asia/Kabul',
  'thailand': 'Asia/Bangkok',
  'vietnam': 'Asia/Ho_Chi_Minh',
  'cambodia': 'Asia/Phnom_Penh',
  'laos': 'Asia/Vientiane',
  'myanmar': 'Asia/Yangon',
  'burma': 'Asia/Yangon',
  'singapore': 'Asia/Singapore',
  'malaysia': 'Asia/Kuala_Lumpur',
  'philippines': 'Asia/Manila',
  'japan': 'Asia/Tokyo',
  'south korea': 'Asia/Seoul',
  'korea': 'Asia/Seoul',
  'north korea': 'Asia/Pyongyang',
  'china': 'Asia/Shanghai',
  'taiwan': 'Asia/Taipei',
  'hong kong': 'Asia/Hong_Kong',
  'macau': 'Asia/Macau',
  'mongolia': 'Asia/Ulaanbaatar',
  'united kingdom': 'Europe/London',
  'uk': 'Europe/London',
  'england': 'Europe/London',
  'scotland': 'Europe/London',
  'wales': 'Europe/London',
  'northern ireland': 'Europe/London',
  'ireland': 'Europe/Dublin',
  'france': 'Europe/Paris',
  'germany': 'Europe/Berlin',
  'spain': 'Europe/Madrid',
  'portugal': 'Europe/Lisbon',
  'italy': 'Europe/Rome',
  'netherlands': 'Europe/Amsterdam',
  'belgium': 'Europe/Brussels',
  'luxembourg': 'Europe/Luxembourg',
  'switzerland': 'Europe/Zurich',
  'austria': 'Europe/Vienna',
  'czech republic': 'Europe/Prague',
  'czechia': 'Europe/Prague',
  'slovakia': 'Europe/Bratislava',
  'poland': 'Europe/Warsaw',
  'hungary': 'Europe/Budapest',
  'slovenia': 'Europe/Ljubljana',
  'croatia': 'Europe/Zagreb',
  'serbia': 'Europe/Belgrade',
  'bosnia and herzegovina': 'Europe/Sarajevo',
  'north macedonia': 'Europe/Skopje',
  'albania': 'Europe/Tirane',
  'bulgaria': 'Europe/Sofia',
  'romania': 'Europe/Bucharest',
  'greece': 'Europe/Athens',
  'turkey': 'Europe/Istanbul',
  'ukraine': 'Europe/Kiev',
  'belarus': 'Europe/Minsk',
  'sweden': 'Europe/Stockholm',
  'norway': 'Europe/Oslo',
  'denmark': 'Europe/Copenhagen',
  'finland': 'Europe/Helsinki',
  'iceland': 'Atlantic/Reykjavik',
  'estonia': 'Europe/Tallinn',
  'latvia': 'Europe/Riga',
  'lithuania': 'Europe/Vilnius',
  'united arab emirates': 'Asia/Dubai',
  'uae': 'Asia/Dubai',
  'qatar': 'Asia/Qatar',
  'saudi arabia': 'Asia/Riyadh',
  'kuwait': 'Asia/Kuwait',
  'bahrain': 'Asia/Bahrain',
  'oman': 'Asia/Muscat',
  'iran': 'Asia/Tehran',
  'iraq': 'Asia/Baghdad',
  'lebanon': 'Asia/Beirut',
  'syria': 'Asia/Damascus',
  'jordan': 'Asia/Amman',
  'israel': 'Asia/Jerusalem',
  'palestine': 'Asia/Hebron',
  'egypt': 'Africa/Cairo',
  'morocco': 'Africa/Casablanca',
  'tunisia': 'Africa/Tunis',
  'algeria': 'Africa/Algiers',
  'libya': 'Africa/Tripoli',
  'sudan': 'Africa/Khartoum',
  'ethiopia': 'Africa/Addis_Ababa',
  'kenya': 'Africa/Nairobi',
  'uganda': 'Africa/Kampala',
  'tanzania': 'Africa/Dar_es_Salaam',
  'rwanda': 'Africa/Kigali',
  'south africa': 'Africa/Johannesburg',
  'zimbabwe': 'Africa/Harare',
  'zambia': 'Africa/Lusaka',
  'mozambique': 'Africa/Maputo',
  'botswana': 'Africa/Gaborone',
  'namibia': 'Africa/Windhoek',
  'nigeria': 'Africa/Lagos',
  'ghana': 'Africa/Accra',
  'mauritius': 'Indian/Mauritius',
  'seychelles': 'Indian/Mahe',
  'argentina': 'America/Argentina/Buenos_Aires',
  'chile': 'America/Santiago',
  'peru': 'America/Lima',
  'colombia': 'America/Bogota',
  'ecuador': 'America/Guayaquil',
  'venezuela': 'America/Caracas',
  'bolivia': 'America/La_Paz',
  'paraguay': 'America/Asuncion',
  'uruguay': 'America/Montevideo',
  'guyana': 'America/Guyana',
  'suriname': 'America/Paramaribo',
  'cuba': 'America/Havana',
  'jamaica': 'America/Jamaica',
  'puerto rico': 'America/Puerto_Rico',
  'dominican republic': 'America/Santo_Domingo',
  'haiti': 'America/Port-au-Prince',
  'panama': 'America/Panama',
  'costa rica': 'America/Costa_Rica',
  'guatemala': 'America/Guatemala',
  'honduras': 'America/Tegucigalpa',
  'el salvador': 'America/El_Salvador',
  'nicaragua': 'America/Managua',
  'belize': 'America/Belize',
  'new zealand': 'Pacific/Auckland',
  'fiji': 'Pacific/Fiji',
  'samoa': 'Pacific/Apia',
  'french polynesia': 'Pacific/Tahiti',
  'azerbaijan': 'Asia/Baku',
  'georgia': 'Asia/Tbilisi',
  'armenia': 'Asia/Yerevan',
  'uzbekistan': 'Asia/Tashkent',
  'kyrgyzstan': 'Asia/Bishkek',
  'tajikistan': 'Asia/Dushanbe',
  'turkmenistan': 'Asia/Ashgabat',
};

function normalize(name) {
  if (!name || typeof name !== 'string') return '';
  return name
    .toLowerCase()
    .trim()
    .replace(/[.,]/g, '')
    .replace(/\s+/g, ' ');
}

export function getTimezoneForCity(cityName) {
  const key = normalize(cityName);
  if (!key) return null;
  return CITY_TZ[key] || null;
}

export function getTimezoneForCountry(countryName) {
  const key = normalize(countryName);
  if (!key) return null;
  return COUNTRY_TZ[key] || null;
}

export function resolveTimezone(locationData) {
  if (!locationData || typeof locationData !== 'object') return null;

  const cityCandidates = [
    locationData.city,
    locationData.areaName,
  ].filter(Boolean);

  for (const candidate of cityCandidates) {
    const tz = getTimezoneForCity(candidate);
    if (tz) return tz;
  }

  if (locationData.country) {
    const tz = getTimezoneForCountry(locationData.country);
    if (tz) return tz;
  }

  return null;
}

export default {
  getTimezoneForCity,
  getTimezoneForCountry,
  resolveTimezone,
};
